name: build

on:
  push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        target:
          - windows
          # - linux
          # - macosx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make --debug=b build-${{ matrix.target }}
      - name: Find Archive
        run: |
          echo "tar_asset_path=$(ls target/release/*.tar.gz)" >> "$GITHUB_ENV"
          echo "tar_asset_name=$(basename $(ls target/release/*.tar.gz))" >> "$GITHUB_ENV"
          echo "sha256_asset_path=$(ls target/release/*.tar.gz.sha256)" >> "$GITHUB_ENV"
          echo "sha256_asset_name=$(basename $(ls target/release/*.tar.gz.sha256))" >> "$GITHUB_ENV"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ env.tar_asset_path }}
          asset_name: ${{ env.tar_asset_name }}
          asset_content_type: application/gzip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{ env.sha256_asset_path }}
          asset_name: ${{ env.sha256_asset_name }}
          asset_content_type: text/plain