name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        target:
          - windows
          - linux
          - macosx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: build/${{ matrix.target }}
          key: ${{ matrix.target }}
      - run: make build-${{ matrix.target }}
      - run: make push-${{ matrix.target }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
