name: build

on:
  push

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get commit SHA
        run: echo "commit_sha=$(echo $GITHUB_SHA | head -c 7)" >> "$GITHUB_ENV"
      - name: Create Release
        continue-on-error: true
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.0-rc.${{ env.commit_sha }}
          release_name: Release 1.0.0-rc.${{ env.commit_sha }}
          draft: false
          prerelease: true
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Check for submodule changes
        run: echo "external_submodules_sha256=$(git submodule status | sha256sum | head -c 64)" >> "$GITHUB_ENV"
      - name: Cache submodules
        id: cache
        uses: actions/cache@v3
        with:
          path: external
          key: external-${{ env.external_submodules_sha256 }}
      - name: Update submodules
        if: steps.cache.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive
      - name: Save source cache
        uses: actions/cache/save@v3
        with:
          path: .
          key: source
      # - name: Archive source
      #   run: tar --create --verbose --exclude .git --file source.tar .
      # - name: Create source artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: source
      #     path: source.tar
  build:
    needs: [release, checkout]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - windows
          # - linux
          # - macosx
    steps:
      # - name: Download source artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: source
      # - name: Extract source
      #   run: tar --extract --verbose --file source.tar .
      - name: Restore source cache
        uses: actions/cache/save@v3
        with:
          path: .
          key: source
      - name: Restore build cache
        uses: actions/cache/restore@v3
        with:
          path: build/${{ matrix.target }}
          key: build-${{ matrix.target }}
      - name: Build ${{ matrix.target }} release target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make build-${{ matrix.target }}
      - name: Save build cache
        uses: actions/cache/save@v3
        with:
          path: build/${{ matrix.target }}
          key: build-${{ matrix.target }}
      - name: Find release archive in target directory
        run: |
          echo "archive_asset_path=$(find target/release -name *.zip -name *.tar.gz)" >> "$GITHUB_ENV"
          echo "archive_asset_name=$(basename ${{ env.tar_asset_path }})" >> "$GITHUB_ENV"
          echo "archive_asset_content_type=$(file --mime-type -b ${{ env.tar_asset_path }})" >> "$GITHUB_ENV"
          echo "sha256_asset_path=$(find target/release -name *.sha256)" >> "$GITHUB_ENV"
          echo "sha256_asset_name=$(basename ${{ env.sha256_asset_path }})" >> "$GITHUB_ENV"
          echo "sha256_asset_content_type=$(file --mime-type -b ${{ env.sha256_asset_name }})" >> "$GITHUB_ENV"
      - name: Upload archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ env.archive_asset_path }}
          asset_name: ${{ env.archive_asset_name }}
          asset_content_type: ${{ env.archive_asset_content_type }}
      - name: Upload sha256
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ env.sha256_asset_path }}
          asset_name: ${{ env.sha256_asset_name }}
          asset_content_type: ${{ env.sha256_asset_content_type }}
